### ISSUE TITLE
Specified signature is not matched

### ISSUE THREAD

**Issue by ericwuu2** [87Hz/aliyun-sms#1]
作者您好~
昨天利用相同的參數(accessKeyId, accessKeySecret, signName, templateCode)進行調用，
可以成功發訊息，但今天就會出現訊息 "Specified signature is not matched with our calculation."，
不知道是不是Aliyun官方更動了什麼

**Comment by 87Hz** [comment]
eric, 您好,很抱歉這麼晚才回復您的消息.我剛剛測試了一下,我這邊是可以成功發送SMS的(28 Nov 2017 8:57am).方便的話您可以再測試一下嗎?有可能是當時Aliyun的伺服器宕機.

如果測試成功的話,請回復,我就close這個issue.

**Comment by ericwuu2** [comment]
之前測試成功，感謝您!!
